travis:
  secure:
    BINSTAR_TOKEN: mQ4q7NpFFrsguAs3kp9V1KLF/vN0ohbw+Tq3aRLFft20KC9S6VSidPwSOorcUJ/1/3HRIHwHdkm9dNgQcrqLgktZj7Zyadu57+9TKcYnH6XPgZRJ5wOa7T7h3ICUW4PgPMyU7+NF+/Wl8yik3/zYKyMp79ZrWdj138K8mvIrbHzz+pcvCkeai9NfkM4HcZXkDpm6AioJOZQuLxKdkmoDVsmsl+wQOcF/Vlrw9CFBEj0h7kxzBABkcVRqqrP0xhx0uW16tvjIyzccu11Nm+eMrMrDG+zfD1MexJgC7TfsDsjPsGpRuN+sfDOMoaRc+ygDjPjsEQqLqQuFt2hyculyxBuoXQv7EK0siUTiozaUPy3f6XpAUlQMw3+D4AwAWPCg1ML5Kz2RMZDwDh03sd764Gg/PWM9fWeIiUHUILktPb5x9CCczfuyl/ttEkZTK/+AjUAJo3JYDBz6tHgV7d8gexy0X7NaGLI92KrgMaUT7bvVgcktZU3+pOhW2dTfiogy8uPyZo+YOE+LLeLHf40pFD79JrxGsk36OTz8h9m65G/sVigbfMHzjpqxBgiUGH6vSYFVSaUZHFpGm0c+m2oKX6hI6omNsdfdG/IOFtYm4xg5WJqJpWpWW5bPV5H42Bc1ulerNx5WzUB0LmF82auiUmRkJTheMt5N9DZIiqiaC9c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
